function contact_menu(){

$items = array(

 'title' => 'Contact Form',
 'description' => 'Another Contact Form',
 'page callback' => 'drupal_get_form',
 'page arguments' => array('contact_form'),
 'access arguments' => array('access content'),
 'type' => MENU_NORMAL_ITEM,
);

$items = array(

 'title' => 'Contact Form',
 'description' => 'A great Contact Form',
 'page callback' => 'drupal_get_form',
 'page arguments' => array('contact_form'),
 'access arguments' => array('access content'),
 'type' => MENU_NORMAL_ITEM,
);

return $items;
}


function contact_form(){

  $form['name'] = array(
    '#title' => t('Name'),
    '#type' => 'textfield'),
    '#required' => TRUE,
  );

  $form['email'] = array(

    '#title' => t('Your E-Mail'),
    '#type' => 'textfield',
    '#required' => TRUE,
  )

return $form;

}
